language:
   - python

before_script:
   - gem install travis

script:
   - echo "LET's SKIP BUILD and TRIGGER test-ci-build"

after_script:
   - chmod +x better_trigger.sh
   - ./better_trigger.sh staiyeba test-ci-build master $TRAVIS_ACCESS_TOKEN
