os: osx
language:
   - python

python:
   - "2.6"

before_script:
   - gem install travis

script:
   - echo "LET's SKIP BUILD and TRIGGER test-ci-build"

after_script:
   - chmod +x trigger.sh
   - ./trigger.sh staiyeba test-ci-build master $TRAVIS_ACCESS_TOKEN
